### ISSUE TITLE
Zkontrolovat číselník mzdových tříd oproti mzdovému předpisu

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/ciselniky#1]
https://data.mff.cuni.cz/datová-sada?iri=https%3A%2F%2Fdata.mff.cuni.cz%2Fzdroj%2Fdatové-sady%2Fčíselníky%2Fmzdové-třídy

**Comment by JiriSkalicky** [comment]
Existuje jen 8 mzdových tříd pro "Ostatní pracovníky" `https://cuni.cz/UK-8897.html`
Prosím @jakubklimek o úpravu ve specifikaci (odstranit třídy 10 až 15).

**Comment by JiriSkalicky** [comment]
Ahah, samozřejmě, díky!
